
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    use-dns-for-fetching-service-urls:
      defaultZone: http://localhost:8761/eureka
